/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbc_search;

import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QuerySolution;
import org.apache.jena.query.ResultSet;
import org.apache.jena.rdf.model.RDFNode;
import static sbc_search.buscardor.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author crismajovi
 */
public class detallador extends javax.swing.JInternalFrame {

    String service = "http://localhost:8890/sparql";
    String defaultGraph = "http://localhost:8890/vivero";

    public detallador() {
        initComponents();
        if (lb_id_check.getText().equals("1")) {
            String pal = palabra_hidden.getText();
            rsp2(pal);
        }
        if (lb_id_check.getText().equals("2")) {
            String pal = palabra_hidden.getText();
            rsp1(pal);
        }
        if (lb_id_check.getText().equals("2")) {
            String pal = palabra_hidden.getText();
            rsp1(pal);
        }
        if (lb_id_check.getText().equals("3")) {
            System.out.println(".......la opcion 2");
//            String pal = palabra_hidden.getText();
//            rsp1(pal);
        }

    }

    public void rsp1(String pal) {
        txt_det_bus.append("------------------------------------------------" + "\n");
        txt_det_bus.append("RESULTADO DE BUSQUEDA POR PLANTA\n");

        String queryString = "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> "
                + "PREFIX dbo: <http://dbpedia.org/ontology/> "
                + "PREFIX schema: <http://www.w3.org/2000/01/rdf-schema#> "
                + "PREFIX dct: <http://purl.org/dc/terms/> "
                + "PREFIX skos: <http://www.w3.org/2004/02/skos/core#> "
                + "PREFIX dbo: <http://dbpedia.org/ontology/> "
                + "PREFIX wo: <http://purl.org/ontology/wo/> "
                + "SELECT DISTINCT ?nombre ?g ?f ?label ?abs "
                + "WHERE {"
                + "?Planta rdf:type dbo:Plant ; schema:label ?label ; dbo:name ?nombre ; dbo:Abstract ?abs ; wo:genus ?g ; wo:family ?f ."
                + "FILTER regex(?nombre , '" + pal + "','i')}limit 1";
        pregunta2(queryString);
    }
    public void rsp2(String pal) {
        txt_det_bus.append("------------------------------------------------" + "\n");
        txt_det_bus.append("RESULTADO DE BUSQUEDA POR PLANTA\n"+pal);


    }

    public void pregunta2(String queryString) {
        //QueryExecution qexec1 = QueryExecutionFactory.sparqlService(service, queryString, defaultGraph);
        QueryExecution qexec1 = QueryExecutionFactory.sparqlService(service, queryString);
        ResultSet results = qexec1.execSelect();
        while (results.hasNext()) {
            QuerySolution sol = results.nextSolution();
            RDFNode nombre = sol.get("nombre");
            RDFNode abs = sol.get("g");
            RDFNode label = sol.get("f");
            RDFNode cat = sol.get("label");
            RDFNode plan = sol.get("abs");

            txt_det_bus.append("------------------------------------------------" + "\n");
            txt_det_bus.append("Nombre de Planta: " + "\n" + nombre.toString() + "\n");
            txt_det_bus.append("------------------------------------------------" + "\n");
            txt_det_bus.append("Genus : " + "\n" + abs.toString() + "\n");
            txt_det_bus.append("------------------------------------------------" + "\n");
            txt_det_bus.append("Family: " + "\n" + label.toString() + "\n");
            txt_det_bus.append("------------------------------------------------" + "\n");
            txt_det_bus.append("Nombre Cientifico : " + "\n" + cat.toString() + "\n");
            txt_det_bus.append("------------------------------------------------" + "\n");
            txt_det_bus.append("Abstracto : " + "\n" + plan.toString() + "\n");
            txt_det_bus.append("------------------------------------------------" + "\n");
        }
        //System.out.close();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_det_bus = new javax.swing.JTextArea();

        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        setClosable(true);

        txt_det_bus.setColumns(20);
        txt_det_bus.setRows(5);
        jScrollPane2.setViewportView(txt_det_bus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_det_bus;
    // End of variables declaration//GEN-END:variables
}
